set_audio_output:
  description: "Set the audio output source for the OREI matrix switch."
  fields:
    source:
      description: "Audio source to select. 0 = follow window selected source; 1..4 = HDMI 1..4."
      example: 1
    entry_id:
      description: "Optional config entry ID when multiple OREI devices are configured."
      example: "abcdef1234567890"

set_multiview:
  description: "Set the multi-view display mode for the OREI matrix switch."
  fields:
    mode:
      description: "Multi-view mode to select. 1 = single screen, 2 = PIP, 3 = PBP, 4 = triple screen, 5 = quad screen."
      example: 1
      selector:
        select:
          options:
            - value: "1"
              label: "Single screen"
            - value: "2"
              label: "PIP"
            - value: "3"
              label: "PBP"
            - value: "4"
              label: "Triple screen"
            - value: "5"
              label: "Quad screen"
    entry_id:
      description: "Optional config entry ID when multiple OREI devices are configured."
      example: "abcdef1234567890"

set_window_input:
  description: "Set the HDMI input for a specific window in the current multiview layout."
  fields:
    window:
      description: "Window number to set (1..4)."
      example: 1
      selector:
        select:
          options:
            - value: "1"
              label: "Window 1"
            - value: "2"
              label: "Window 2"
            - value: "3"
              label: "Window 3"
            - value: "4"
              label: "Window 4"
    source:
      description: "HDMI input to select for the window (1..4)."
      example: 1
      selector:
        select:
          options:
            - value: "1"
              label: "HDMI 1"
            - value: "2"
              label: "HDMI 2"
            - value: "3"
              label: "HDMI 3"
            - value: "4"
              label: "HDMI 4"
    entry_id:
      description: "Optional config entry ID when multiple OREI devices are configured."
      example: "abcdef1234567890"

set_pip_position:
  description: "Set the PIP window position. 1=Left Top, 2=Left Bottom, 3=Right Top, 4=Right Bottom"
  fields:
    position:
      description: "PIP position to select (1..4)."
      example: 1
      selector:
        select:
          options:
            - value: "1"
              label: "Left Top"
            - value: "2"
              label: "Left Bottom"
            - value: "3"
              label: "Right Top"
            - value: "4"
              label: "Right Bottom"
    entry_id:
      description: "Optional config entry ID when multiple OREI devices are configured."
      example: "abcdef1234567890"

set_pip_size:
  description: "Set the PIP window size. 1=small, 2=middle, 3=large"
  fields:
    size:
      description: "PIP size to select (1..3)."
      example: 2
      selector:
        select:
          options:
            - value: "1"
              label: "Small"
            - value: "2"
              label: "Middle"
            - value: "3"
              label: "Large"
    entry_id:
      description: "Optional config entry ID when multiple OREI devices are configured."
      example: "abcdef1234567890"
